### ISSUE TITLE
VSCode incorrect decorated func hint

### ISSUE THREAD

**Issue by iperov** [Stewori/pytypes#119] opened 2023-01-01 11:52 UTC
unable to determine func signature in hint

![Code_2023-01-01_15-48-32](https://user-images.githubusercontent.com/8076202/210169636-fd713017-f6f9-48c2-84f7-447649d9d310.png)

________________________

with usual decorator all fine

![Code_2023-01-01_15-52-14](https://user-images.githubusercontent.com/8076202/210169745-9f4b9b1a-8085-4185-9353-afa4948fb114.png)

**Comment by Stewori** [comment] 2023-01-01 14:16
Note that I am not working on pytypes at the moment. That said, this does look more like as VSCode issue; there is a helper ``pytypes.util._actualfunc`` that retrieves the backing function if they fail to retrieve it their way. Since it is impossible to tell what VSCode is actually doing, that cannot be fixed in pytypes.
For pytypes issues, please provide the stacktrace (place ``pytypes.clean_traceback = False`` at top to reveal pytypes-internal part of the stack trace) and a reproducible example.
Also, you can avoid decorator issues by using [profiler mode](https://github.com/Stewori/pytypes#global-mode-via-profilers).

**Comment by iperov** [comment] 2023-01-01 14:19
> look more like as VSCode issue

i don't think so.

this solution works 
```
from typing import TypeVar

import pytypes

T = TypeVar('T')

def typechecked(func : T) -> T:
    return pytypes.typechecked(func)
```

**Comment by iperov** [comment] 2023-01-01 14:22
also, can you recommend a similar library that works with Generic?

**Comment by Stewori** [comment] 2023-01-01 15:42
> this solution works

For some reason VSCode tries to determine the arg types of a function. That solution likely won't help it access the original types. Anyway, if it silences the error, your adjustment is a simple enough fix.
Changing the ``typechecked`` signature in ``typechecker.py`` should do the same trick. If it is as simple as that I can make that change. Can you confirm that making the change in ``typechecker.py`` fixes it for you? (changing line 1007 from ``def typechecked(memb):`` to ``def typechecked(memb: T)->T:``)

I am not aware of any other lib that works with Generic, but I might not have an up to date picture. Maintenance of such a feature is immensely painful because of rapid changes in the typing module. pytypes only works for Pythons up to 3.8 as of this writing.

**Comment by iperov** [comment] 2023-01-01 15:56
the bug reproduced in python 3.8.10

> def typechecked(memb: T)->T:)

unfortunately does not work. May be the bug in vscode.

> immensely painful because of rapid changes in the typing module

I understand, that's sad. It seems only your library support Generic type checking.

**Comment by iperov** [comment] 2023-01-01 15:59
by the way, decorator should return func wrapper
```
def typechecked(memb : T) -> T:
    if not pytypes.checking_enabled:
        return memb
```
I think such code confuses hint evaluator

**Comment by Andreypetrov10** [comment] 2023-01-09 09:43
> не удается определить подпись func в подсказка > > ![ Код_2023-01-01_15-48-32] (https://user-images.githubusercontent.com/8076202/210169636-fd713017-f6f9-48c2-84f7-447649d9d310.png) > > с обычным декоратором все в порядке > > ![ Код_2023-01-01_15-52-14] (https://user-images.githubusercontent.com/8076202/210169745-9f4b9b1a-8085-4185-9353-afa4948fb114.png) 



Иван добрый день , меня зовут Андрей запустил проекты Антивирус Гризли про , online-ocenka.ru оценка для нотариусов , к вам есть деловое предложение. Свяжитесь со мной пожалуйста , не могу найти как вам написать. ТГ @andrei_kratkiy

**Comment by Stewori** [comment] 2023-01-09 14:27
(deleted spam)

**Closed as completed** 2023-05-12 08:50 UTC
